# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 220807547afd4e161d1c65d4f7194e7f3ab2320ed67355b420e99f865417aafa99c33460821481d7209732b4ccbd1df7f0798fc0236e0ec064ddfd387abfa6b2

test:
  secret_key_base: 7c892ec4fbc49a9f5bbee6d4c5478548ac228739040de201b6922bd27227d97c0d20bafdc4cc25f4d4ad13860f48f6988f966a5be749f7759c87b4f427489781

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
