# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36f2948772562a0d5bdfd744ae72fbaa1214c51d2b1c2a10235d6b042ae9f9cd71ed0a0f9ed260cf89bbf0319c96fb15fed53a0f28a53a9bd7953659ef76535d

test:
  secret_key_base: e534da0bc424ff969d5514976f72df69ab53511907d67444aeaab0491bf799ebbe5f0ad95fbf6e8a1f0078231ea0be740e5918e046e781b87d9bdae1d2b10c79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
